name: hexdino
base: core22
version: 0.1.3
license: MIT
summary: A hex editor with vim like keybindings written in Rust.
description: |
  A hex editor with vim like keybindings written in Rust.

confinement: devmode

parts:
  rust-deps:
    plugin: nil
  hexdino:
    plugin: rust
    source: https://github.com/Luz/hexdino.git
  after: [rust-deps]

apps:
  hexdino:
    command: bin/hexdino
