name: hexdino
title: hexdino
base: core22
icon: https://raw.githubusercontent.com/Luz/hexdino/master/logo.png
version: 0.1.3
license: MIT
website: https://github.com/Luz/hexdino
source-code: https://github.com/Luz/hexdino
issues: https://github.com/Luz/hexdino/issues
summary: A hex editor with vim like keybindings written in Rust.
description: |
  A hex editor with vim like keybindings written in Rust.

grade: stable
confinement: strict

parts:
  hexdino:
    plugin: rust
    build-packages: [cargo]
    source: https://github.com/Luz/hexdino.git

apps:
  hexdino:
    command: bin/hexdino
